### ISSUE TITLE
ImmMap adds same keys as separate key-values

### ISSUE THREAD

**Issue by Imunhatep** [phunkie/phunkie#18] opened 2019-04-30 16:25 UTC
Not sure if this behavior is by design, since "promote()" used in keys returns objects.. But I would expect returning new instances of ImmMap with overwritten value instead of duplicated keys

**Comment by MarcelloDuarte** [comment] 2019-05-05 18:58
That doesn't sound like intended behaviour. I am marking this as a bug. Internally ImmMap uses SPL ObjectStorage attach method. We probably need some manual verification of the key identity before promoting the key to the Integer or String object, to guarantee uniqueness.

**Closed** 2020-03-29 19:12 UTC
Labels: bug
